# .github/workflows/sonarcloud.yml
name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonarcloud-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarScanner
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_USER_HOME: ${{ github.workspace }}/.sonar
